# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dimensional}
  s.version = "2.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Hapgood"]
  s.date = %q{2010-02-17}
  s.description = %q{    Dimensional provides handling for dimensional values (numbers with units).  Dimensional values
    can be parsed, stored, converted and formatted for output.
}
  s.email = %q{cch1@hapgoods.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README",
     "Rakefile",
     "lib/dimensional.rb",
     "lib/dimensional/configurator.rb",
     "lib/dimensional/dimension.rb",
     "lib/dimensional/locale.rb",
     "lib/dimensional/metric.rb",
     "lib/dimensional/system.rb",
     "lib/dimensional/unit.rb",
     "lib/dimensional/version.rb",
     "test/configurator_test.rb",
     "test/demo.rb",
     "test/dimension_test.rb",
     "test/dimensional_test.rb",
     "test/helper.rb",
     "test/locale_test.rb",
     "test/metric_test.rb",
     "test/system_test.rb",
     "test/unit_test.rb"
  ]
  s.homepage = %q{http://cho.hapgoods.com/dimensional}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.6.8")
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Dimensional provides handling for numbers with units.}
  s.test_files = [
    "test/helper.rb",
     "test/configurator_test.rb",
     "test/dimension_test.rb",
     "test/dimensional_test.rb",
     "test/locale_test.rb",
     "test/metric_test.rb",
     "test/system_test.rb",
     "test/unit_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

